package com.notifyhub.communication.service;

import com.github.jknack.handlebars.Handlebars;
import com.github.jknack.handlebars.Template;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import lombok.extern.slf4j.Slf4j;
import org.jsoup.Jsoup;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Document;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.UUID;

@Service
@Slf4j
public class PdfGenerationService {

    @Value("${file.storage.pdf-directory}")
    private String PDF_DIR;

    private final Handlebars handlebars;

    public PdfGenerationService() {
        this.handlebars = new Handlebars();

        // Generated by ChatGPT to register custom helper
        this.handlebars.registerHelper("eachPage", (context, options) -> {
            if (context instanceof Iterable) {
                java.util.List<Object> list = new java.util.ArrayList<>();
                for (Object item : (Iterable<?>) context) {
                    list.add(item);
                }

                int size = 5;
                Object sizeObj = options.hash.get("size");
                if (sizeObj instanceof Number) {
                    size = ((Number) sizeObj).intValue();
                } else if (sizeObj instanceof String) {
                    try {
                        size = Integer.parseInt((String) sizeObj);
                    } catch (NumberFormatException e) {
                        // fallback to 5
                    }
                }

                int totalPages = (int) Math.ceil((double) list.size() / size);
                if (totalPages == 0)
                    totalPages = 1;

                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < list.size(); i += size) {
                    int end = Math.min(i + size, list.size());
                    java.util.List<Object> chunk = list.subList(i, end);
                    int pageNum = (i / size) + 1;

                    Map<String, Object> pageContext = new java.util.HashMap<>();
                    if (options.context.model() instanceof Map) {
                        @SuppressWarnings("unchecked")
                        Map<String, Object> parentModel = (Map<String, Object>) options.context
                                .model();
                        pageContext.putAll(parentModel);
                    }
                    pageContext.put("thisPageItems", chunk);
                    pageContext.put("pageNumber", pageNum);
                    pageContext.put("totalPages", totalPages);
                    pageContext.put("isLastPage", pageNum == totalPages);

                    sb.append(options.fn(pageContext));
                }
                return sb.toString();
            }
            return "";
        });
    }



    public String generatePdf(UUID communicationId, String templateHtml, String templateCss,
            Map<String, Object> payload) throws Exception {
        Path path = Paths.get(PDF_DIR);
        if (!Files.exists(path)) {
            Files.createDirectories(path);
        }

        // 1. Compile and render with real Handlebars — same {{ }}, {{#each}}, {{#if}}
        // syntax
        // your templates already use (e.g. {{#each items.item}}, {{customer.name}}),
        // just backed by a proper parser instead of hand-rolled regex.

        Template compiledTemplate = handlebars.compileInline(templateHtml);
        String renderedHtml = compiledTemplate.apply(payload);

        // 2. Wrap in a full document if the template is just a body fragment, and
        // inject CSS
        String lowerHtml = renderedHtml.toLowerCase();

        if (!lowerHtml.contains("<html")) {
            String cssBlock = (templateCss != null && !templateCss.trim().isEmpty())
                    ? templateCss
                    : "body { font-family: sans-serif; padding: 20px; }";
            renderedHtml = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\" /><style>"
                    + cssBlock
                    + "</style></head><body>"
                    + renderedHtml
                    + "</body></html>";
        } else if (templateCss != null && !templateCss.trim().isEmpty() && lowerHtml.contains("</head>")) {
            int idx = lowerHtml.indexOf("</head>");
            renderedHtml = renderedHtml.substring(0, idx)
                    + "<style>" + templateCss + "</style>"
                    + renderedHtml.substring(idx);
        }


        String targetPdfPath = PDF_DIR + "/" + communicationId + "_invoice.pdf";
        File pdfFile = new File(targetPdfPath);

        // 3. openhtmltopdf's default HTML loader needs strict, well-formed XHTML —
        // route the rendered output through Jsoup (parses it the way a browser would,
        // then serializes clean XHTML) before handing it to the PDF renderer.
        Document jsoupDoc = Jsoup.parse(renderedHtml);
        jsoupDoc.head();
        jsoupDoc.head().append("\n<style>\n" +
                "  .page:first-child, .page-container:first-child, .invoice-container:first-child, .page-break:first-child, div.page:first-of-type {\n" +
                "    page-break-before: avoid !important;\n" +
                "    page-break-before: auto !important;\n" +
                "  }\n" +
                "  .page:last-child, .page-container:last-child, .invoice-container:last-child, .page-break:last-child, div.page:last-of-type {\n" +
                "    page-break-after: avoid !important;\n" +
                "    page-break-after: auto !important;\n" +
                "  }\n" +
                "</style>\n");
        jsoupDoc.outputSettings().syntax(Document.OutputSettings.Syntax.xml);

        org.w3c.dom.Document xhtmlDoc = new W3CDom().fromJsoup(jsoupDoc);

        try (OutputStream os = new FileOutputStream(pdfFile)) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withW3cDocument(xhtmlDoc, null);
            builder.toStream(os);
            builder.run();
        }

        log.info("PDF compiled and stored successfully at: {}", targetPdfPath);
        return pdfFile.getAbsolutePath();
    }
}