package com.notifyhub.core.batch.communication;

import org.w3c.dom.*;
import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.StringReader;
import java.util.*;

public class XmlValidator {

    // record to store the errors
    public record XmlValidationError(String path, String errorCode, String message) { }


    public static List<XmlValidationError> validateXml(String sampleXml, String actualXml) {
        try {
            Document sampleDocument = parseXml(sampleXml);
            Document actualDocument = parseXml(actualXml);

            List<XmlValidationError> errors = new ArrayList<>();

            Element sampleRoot = sampleDocument.getDocumentElement();
            Element actualRoot = actualDocument.getDocumentElement();

            // Check root
            if (!sampleRoot.getNodeName().equals(actualRoot.getNodeName())) {
                errors.add(new XmlValidationError(
                        "",
                        "INVALID_ROOT",
                        "Expected root node '" + sampleRoot.getNodeName() + "' but found '" + actualRoot.getNodeName() + "'"
                ));
                return errors;
            }

            // Recursively validate
            validateNode(
                    sampleRoot,
                    actualRoot,
                    sampleRoot.getNodeName(),
                    errors
            );

            return errors.isEmpty() ? null : errors;

        } catch (Exception e) {
            return List.of(
                    new XmlValidationError(
                            "",
                            "INVALID_XML",
                            e.getMessage()
                    )
            );
        }
    }

    private static void validateNode(
            Element expectedNode,
            Element actualNode,
            String path,
            List<XmlValidationError> errors
    ) {
        Map<String, List<Element>> expectedChildren = getChildElements(expectedNode);
        Map<String, List<Element>> actualChildren = getChildElements(actualNode);

        for (Map.Entry<String, List<Element>> entry : expectedChildren.entrySet()) {
            String nodeName = entry.getKey();
            List<Element> expectedElements = entry.getValue();
            List<Element> actualElements = actualChildren.getOrDefault(nodeName, Collections.emptyList());

            if (actualElements.isEmpty()) {
                errors.add(new XmlValidationError(
                        path + "." + nodeName,
                        "MISSING_NODE",
                        "Expected node '" + nodeName + "' is missing"
                ));
                continue;
            }

            Element templateElement = expectedElements.get(0);
            for (Element actualElement : actualElements) {
                validateNode(
                        templateElement,
                        actualElement,
                        path + "." + nodeName,
                        errors
                );
            }
        }

        for (String actualNodeName : actualChildren.keySet()) {
            if (!expectedChildren.containsKey(actualNodeName)) {
                errors.add(new XmlValidationError(
                        path + "." + actualNodeName,
                        "UNEXPECTED_NODE",
                        "Unexpected node '" + actualNodeName + "'"
                ));
            }
        }
    }

    private static Map<String, List<Element>> getChildElements(Element parent) {
        Map<String, List<Element>> children = new LinkedHashMap<>();
        NodeList nodeList = parent.getChildNodes();

        for (int i = 0; i < nodeList.getLength(); i++) {
            Node node = nodeList.item(i);
            if (node.getNodeType() != Node.ELEMENT_NODE) {
                continue;
            }
            Element element = (Element) node;
            children.computeIfAbsent(element.getNodeName(), key -> new ArrayList<>()).add(element);
        }
        return children;
    }

    // generated by ChatGPT
    private static Document parseXml(String xml) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
        factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
        factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        factory.setXIncludeAware(false);
        factory.setExpandEntityReferences(false);
        DocumentBuilder builder = factory.newDocumentBuilder();
        return builder.parse(new InputSource(new StringReader(xml)));
    }
}
